---
# Generated by Terraform — fill in ansible_host after DHCP reservation
# MAC addresses are output by: terraform output mac_addresses
all:
  vars:
    environment: ${environment}
    ansible_user: deploy
    ansible_ssh_common_args: '-o StrictHostKeyChecking=accept-new'
  children:
    imp_clients:
      hosts:
        imp-client-${environment}:
          ansible_host: "${client_mac}"  # Set DHCP reservation, then replace with IP
    imp_servers:
      hosts:
        imp-server-${environment}:
          ansible_host: "${server_mac}"  # Set DHCP reservation, then replace with IP
    imp_databases:
      hosts:
        imp-db-${environment}:
          ansible_host: "${db_mac}"  # Set DHCP reservation, then replace with IP
    imp_storage:
      hosts:
        imp-minio-${environment}:
          ansible_host: "${minio_mac}"  # Set DHCP reservation, then replace with IP
